palette = "catppuccin_frappe"

# Reorder modules so Kubernetes appears at the end of the left prompt
# Keep a simple set covering common modules used here.
format = "$username@$hostname in $directory $git_branch $git_status $deno $kubernetes$line_break$character"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[character]
# Use `$` as the default prompt symbol instead of the default ❯
success_symbol = '\$ '
error_symbol = '\$ '
vicmd_symbol = '\$ '

[kubernetes]
disabled = false
symbol = "☸ "
# Show context and optionally namespace only; omit user/cluster.
# Parenthesized groups are shown only when variables inside are set.
format = '[$symbol$context( \($namespace\))]($style) '

[username]
# Always show the current username in the prompt
show_always = true
format = '[$user]($style) '

[hostname]
# Always show hostname (not only on SSH)
ssh_only = false
format = '[$hostname]($style)'

[directory]
# Show only the last path segment (folder name)
truncation_length = 1
truncate_to_repo = false
format = '[$path]($style) '
